//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalInformationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCourseDetail
    {
        public int StudentCourseDetailsId { get; set; }
        public int StudentId { get; set; }
        public int CourseId { get; set; }
        public Nullable<System.DateTime> EnrolledDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual CourseInfo CourseInfo { get; set; }
        public virtual StudentInfo StudentInfo { get; set; }
    }
}
